guest_list = ['odelia', 'david b', 'iddo', 'juju', 'safta cat']
guest_list.insert(0,'bob')
print(guest_list)
guest_list.insert(3,'max')
print(guest_list)
guest_list.insert(-1,'harry')
print(guest_list)
print(f" {guest_list[0]} you are invited to dinner")
print(f" {guest_list[1]} you are invited to dinner")
print(f" {guest_list[2]} you are invited to dinner")
print(f" {guest_list[3]} you are invited to dinner")
print(f" {guest_list[4]} you are invited to dinner")
print(f" {guest_list[5]} you are invited to dinner")
print(f" {guest_list[6]} you are invited to dinner")
print("I only have room for 2 people at dinner. Sorry")
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
guest_list.pop()
print(f"Sorry {guest_list[-1]}. We don't have room anymore")
print(guest_list)
print(f"Hey {guest_list[0]}! You're still in!")
print(f"Hey {guest_list[1]}! You're still in!")
del guest_list[1]
print(guest_list)
del guest_list[0]
print(guest_list)