guest_list = ['odelia', 'david b', 'iddo', 'juju', 'safta cat']
guest_list.insert(0,'bob')
print(guest_list)
guest_list.insert(3,'max')
print(guest_list)
guest_list.insert(-1,'harry')
print(guest_list)
print(f" {guest_list[0]} you are invited to dinner")
print(f" {guest_list[1]} you are invited to dinner")
print(f" {guest_list[2]} you are invited to dinner")
print(f" {guest_list[3]} you are invited to dinner")
print(f" {guest_list[4]} you are invited to dinner")
print(f" {guest_list[5]} you are invited to dinner")
print(f" {guest_list[6]} you are invited to dinner")